### ISSUE TITLE
guide page scss/sass toggle doesn't work

### ISSUE THREAD

**Issue by RileyMShea** [sass/sass-site#400] opened 2019-11-02 19:45 UTC
https://sass-lang.com/guide

just jumps down the page when trying to toggle between sass and scss examples

**Comment by nex3** [comment] 2019-11-04 19:44
@adekunleoduye Can you investigate? This sounds similar to the other switcher issues that were happening due to the sticky nav code.

**Comment by adekunleoduye** [comment] 2019-11-05 03:28
@nex3 yeah, I can take a look at it.

**Comment by nex3** [comment] 2019-11-05 03:51
Thanks!

**Comment by dtvn** [comment] 2019-11-05 05:50
So this is just a mirror bug of site right? I hope `sass` format will be kept around, I kinda like it.

**Comment by RileyMShea** [comment] 2019-11-06 02:51
As far as I can tell the site has been this way since October 13th.  It also seems present in the rest of the general documentation outside the introductory guide.

Same issues in the [Oct 13th snapshot](https://web.archive.org/web/20191003120054/https://sass-lang.com/guide) 

Latest date where it's working as intended seems to be [the Oct 3rd snapshot.](https://web.archive.org/web/20191003120054/https://sass-lang.com/guide)

**Comment by nex3** [comment] 2019-11-07 23:39
@adekunleoduye It looks like this is still reproducing... maybe we should roll back sticky navs until we can get it working again?

**Comment by adekunleoduye** [comment] 2019-11-07 23:43
@nex3 yeah, that sounds good to me.

**Comment by nex3** [comment] 2019-11-08 02:04
This has been temporarily fixed by https://github.com/sass/sass-site/pull/407; we still need to figure out why the upgrade caused problems and perhaps why they only seemed to show up in production.

**Comment by nex3** [comment] 2023-04-11 01:05
Closing this out since we plan to move to a totally new site infrastructure anyways so it's unlikely we can roll forward sticky nav code as-is regardless.

**Closed by nex3** 2023-04-11 01:05 UTC
Labels: bug
