### ISSUE TITLE
Code example tabs broken

### ISSUE THREAD

**Issue by chepulis** [sass/sass-site#405] opened 2019-11-07 23:35 UTC
In documentation, clicking on Sass, the arrow or CSS does nothing.

![image](https://user-images.githubusercontent.com/11724303/68436750-8d5ca480-01c7-11ea-9e6b-551e92275da2.png)

In addition, clicking on SCSS jumps viewport to the top of the code block, which while not nonsensical, probably isn't a good experience (it should do nothing, just as indicated by the cursor).

Mac: chrome, firefox, latest.

**Comment by nex3** [comment] 2019-11-07 23:39
Duplicate of #400.

**Closed by nex3** 2019-11-07 23:39 UTC
