### ISSUE TITLE
please host over HTTPS

### ISSUE THREAD

**Issue by ndelangen** [sass/sass-site#197] opened 2017-12-20 07:56 UTC
Your website isn't hosted over https, if tried, there's a browser notification the connection is not secure:

<img width="698" alt="screen shot 2017-12-20 at 08 56 00" src="https://user-images.githubusercontent.com/3070389/34196744-acf5fbc0-e563-11e7-9cfc-ef49f1d032ae.png">

**Comment by nschonni** [comment] 2017-12-21 02:36
Duplicate of #177

**Closed** 2017-12-21 07:25 UTC
